server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://172.17.0.4:27017/ticketing_system
      database: ticketing_system
  elasticsearch:
    uris: http://172.17.0.2:9200

jwt:
  secret: mySecretKeyForJWTTokenGenerationMustBe256BitsLongForHS256Algorithm123456
  expiration: 86400000
